[project]
name = "letsencrypt-domeneshop-paloalto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["pan-python",
                "certbot",
                "certbot-dns-domeneshop"]